config/routes.rb
Rails.application.routes.draw do
  resources :doctors do
  	resources :patients
  end
  root 'doctors#index'
  # root 'doctors#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	has_and_belongs_to_many :patients
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_and_belongs_to_many :doctors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
      @doctors = Doctor.all
  end
   def show
    @d1 = Doctor.find(1)
    @d2 = Doctor.find(2)
    @d3 = Doctor.find(3)
    @p1 = Patient.find(1)
    @p2 = Patient.find(2)
    @p3 = Patient.find(3)
    @p4 = Patient.find(4)
    @p5 = Patient.find(5)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
  	@doctor = Doctor.find_by_id(params[:doctor_id])
		@patients = @doctor.patients
		@patients = Patient.all
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/doctors/index.html.erb
<h1>List of doctor's</h1>

<% @doctors.each do |doctor|%>
    Name: <a href="<%= doctor_patients_path(doctor.id)%>"><%= doctor.name%></a><br>
    Email: <%= doctor.email%><br>
<% end %>
<hr />

app/views/doctors/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Example</title>
</head>
<body>
  <h1>Doctor has_many :appointments<br/>
    Doctor has_many :patients, through: :appointments</h1>
    <h2>Doctor Name: <%= @d1.name %></h2>
    <h3>Doctor <%= @d1.name %>'s patients:</h3>
    <h4>Patient Name: <%= @p1.name %></h4>
    <h4>Patient Email: <%= @p1.email %></h4>
    <br />
    <hr />
    <hr />
    <h1>Patient has_many :appointments<br/>
      Patient has_many :doctors, through: :appointments</h1>
      <h2>Patient Name: <%= @p1.name %></h2>
      <h3>List of Doctors Available:</h3>
      <% @p1.doctors.each do |doctor|%>
      Name: <%= doctor.name%><br>
      Email: <%= doctor.email%><br>
    <% end %>

    
    <h2>Patient Name: <%= @p2.name %></h2>
      <h3>List of Doctors Available:</h3>
      <% @p2.doctors.each do |doctor|%>
      Name: <%= doctor.name%><br>
      Email: <%= doctor.email%><br>
    <% end %>
    <h2>Patient Name: <%= @p3.name %></h2>
      <h3>List of Doctors Available:</h3>
      <% @p3.doctors.each do |doctor|%>
      Name: <%= doctor.name%><br>
      Email: <%= doctor.email%><br>
    <% end %>
    <h2>Patient Name: <%= @p4.name %></h2>
      <h3>List of Doctors Available:</h3>
      <% @p4.doctors.each do |doctor|%>
      Name: <%= doctor.name%><br>
      Email: <%= doctor.email%><br>
    <% end %>
    <h2>Patient Name: <%= @p5.name %></h2>
      <h3>List of Doctors Available:</h3>
      <% @p5.doctors.each do |doctor|%>
      Name: <%= doctor.name%><br>
      Email: <%= doctor.email%><br>
    <% end %>
      <hr/>
      <hr/>
      </body>
      </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HABTMA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/index.html.erb
<h1>Patients belongs to doctors</h1>
<% @patients.each do |patient|%>
    Name: <a href="<%= doctors_path(id: patient.id)%>"><%= patient.name%></a><br>
    Email: <%= patient.email%><br>
<% end %>